// @ts-nocheck
import { app, BrowserWindow, nativeImage, ipcMain, dialog } from "electron";
import { spawn } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

/**
 * Electron shell (PRD §9). In dev it loads the Vite server; in a packaged build
 * it spawns the bundled Substrate server and loads the built web app. Release
 * matrix: macOS DMG, Linux AppImage, Windows NSIS (see package.json build).
 *
 * NOTE: production static serving of the web build from the server process is a
 * follow-up — this slice targets the dev flow (run `pnpm dev`, then `pnpm desktop`).
 */

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const isDev = !app.isPackaged;
let serverProc = null;

// The Substrate mark. Packaged builds use the .icns/.ico generated by
// electron-builder from build/icon.png; this drives the dev dock/taskbar icon
// (otherwise dev shows the generic Electron icon).
const iconPath = path.join(__dirname, "build/icon-512.png");

function startServer() {
  if (isDev) return; // dev runs the server via `pnpm dev:server`
  // Node 24 runs TypeScript natively, so the server entry is its .ts source.
  serverProc = spawn(process.execPath, [path.join(__dirname, "../server/src/index.ts")], {
    stdio: "inherit",
    env: process.env,
  });
}

function createWindow() {
  const win = new BrowserWindow({
    width: 1440,
    height: 900,
    minWidth: 1024,
    minHeight: 640,
    backgroundColor: "#08090b",
    titleBarStyle: "hiddenInset",
    icon: iconPath, // used on Windows/Linux; macOS uses the dock icon below
    webPreferences: { contextIsolation: true, preload: path.join(__dirname, "preload.cjs") },
  });

  // Load the app from the same loopback origin that serves the API/WS/blobs and
  // hosts MCP (the mandrel pattern). Never file:// — that breaks the editor's
  // relative /api, /blobs, /ws calls. In dev the renderer is served by Vite.
  const port = process.env.SUBSTRATE_PORT ?? "4321";
  win.loadURL(isDev ? (process.env.SUBSTRATE_WEB ?? "http://localhost:5173") : `http://localhost:${port}/`);
}

async function waitForServer(port) {
  for (let i = 0; i < 100; i++) {
    try {
      const res = await fetch(`http://localhost:${port}/api/status`);
      if (res.ok) return;
    } catch {
      // not up yet
    }
    await new Promise((r) => setTimeout(r, 100));
  }
}

app.whenReady().then(async () => {
  // macOS shows the dock icon from the app bundle when packaged; in dev set it
  // explicitly so the running app carries the Substrate mark, not Electron's.
  if (isDev && process.platform === "darwin" && app.dock) {
    const img = nativeImage.createFromPath(iconPath);
    if (!img.isEmpty()) app.dock.setIcon(img);
  }
  // Native picker for attaching read-only file context to a deck. macOS lets the
  // user choose a folder OR a single file; the server sandboxes whatever is picked.
  ipcMain.handle("substrate:pickPath", async () => {
    const win = BrowserWindow.getFocusedWindow();
    const result = await dialog.showOpenDialog(win ?? undefined, {
      properties: ["openFile", "openDirectory", "multiSelections"],
      message: "Choose folders or files for the agent to read as context",
    });
    // Return ALL chosen paths (the user can multi-select folders/files at once).
    return result.canceled || result.filePaths.length === 0 ? null : result.filePaths;
  });

  // Native export: Electron's renderer has no File System Access write picker, so
  // the web export path silently fails here. Ask for a destination folder and
  // write the bundle with Node fs (honoring "always ask where to download").
  ipcMain.handle("substrate:saveExport", async (_e, payload) => {
    const win = BrowserWindow.getFocusedWindow();
    // The renderer (a loopback http page) is untrusted: reduce every name to a
    // bare basename and reject anything path-bearing, so a crafted name can never
    // write outside the chosen folder. Writes are async to keep the UI responsive.
    const safeName = (name) => {
      const base = path.basename(String(name ?? ""));
      return !base || base === "." || base === ".." || base !== String(name) ? null : base;
    };
    // A single packaged file (e.g. .pptx) → save it directly with a Save-As dialog.
    if (payload.files.length === 1) {
      const file = payload.files[0];
      const result = await dialog.showSaveDialog(win ?? undefined, {
        defaultPath: safeName(file.name) ?? "export",
        message: "Save export",
      });
      if (result.canceled || !result.filePath) return null;
      await fs.promises.writeFile(result.filePath, Buffer.from(file.data));
      return result.filePath;
    }
    // Several files → pick a destination folder and write the bundle into it.
    const result = await dialog.showOpenDialog(win ?? undefined, {
      properties: ["openDirectory", "createDirectory"],
      message: `Choose where to save "${payload.suggestedName}"`,
    });
    if (result.canceled || result.filePaths.length === 0) return null;
    const dest = path.join(result.filePaths[0], safeName(payload.suggestedName) ?? "export");
    await fs.promises.mkdir(dest, { recursive: true });
    for (const file of payload.files) {
      const base = safeName(file.name);
      if (base) await fs.promises.writeFile(path.join(dest, base), Buffer.from(file.data));
    }
    return dest;
  });

  startServer();
  if (!isDev) await waitForServer(process.env.SUBSTRATE_PORT ?? "4321");
  createWindow();
  app.on("activate", () => {
    if (BrowserWindow.getAllWindows().length === 0) createWindow();
  });
});

app.on("window-all-closed", () => {
  if (serverProc) serverProc.kill();
  if (process.platform !== "darwin") app.quit();
});
